### ISSUE TITLE
Run rtx CI for PRs

### ISSUE THREAD

**Issue by kachick** [kachick/asdf-cargo-make#37]
Currently, only scheduled triggers exist because specifying a git-ref is not official.
I'll update after https://github.com/jdxcode/rtx/issues/164.

https://github.com/kachick/asdf-cargo-make/commit/3799033e5cfb578e30f33f307f217bc0bcad5199#diff-5213986343ba5b14a2a002e79125d1b377df7e1f3b1c032ac2a1645ee6ebe2c9R3-R6
https://github.com/kachick/asdf-cargo-make/commit/3799033e5cfb578e30f33f307f217bc0bcad5199#diff-5213986343ba5b14a2a002e79125d1b377df7e1f3b1c032ac2a1645ee6ebe2c9R33-R34

https://github.com/jdxcode/rtx/pull/182 direction is very good, but testing on the plugin side is also useful, I think.

**Comment by jdx** [comment]
I need to implement this: https://asdf-vm.com/plugins/create.html#testing-plugins

EDIT: created https://github.com/jdxcode/rtx/issues/191 to track

**Comment by kachick** [comment]
That will help me a lot! 🙏
